eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: '{cipher}233bd907c35a418801278bd2da2d76e1eb2483d50e9b147a576ee7c537e96017e449eb3b48dac16418855c32f91e2ef8'
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 124563
    url: jdbc:mysql://localhost:3306/sca?useSSL=false

  cloud:
    config:
      uri: http://localhost:8888
    stream:
      bindings:
        output:
          destination: orgChangeTopic
          content-type: application/json
          binder: remote-rabbit
      binders:
        remote-rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 47.94.156.44
                port: 5672
                username: admin
                password: 124563    

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:2000/user
name: prod
