eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 124563
    url: jdbc:mysql://localhost:3306/sca?useSSL=false

  cloud:

    stream:
      bindings:
        output:
          destination: orgChangeTopic
          content-type: application/json
          binder: remote-rabbit
      binders:
        remote-rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 47.94.156.44
                port: 5672
                username: admin
                password: 124563    

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:3000/user
name: prod
