spring:
  datasource:
    password: 124563
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sca?useSSL=false
    username: root
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
  
  redis:
    host: 47.94.156.44
    port: 8090

  cloud:
    stream:
      bindings:
        inboundOrgChange:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
          binder: remote-rabbit
      binders:
        remote-rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 47.94.156.44
                port: 5672
                username: admin
                password: 124563

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka




feign:
  client:
    config:
      organizationservice:
        requestInterceptors:
          - top.yeonon.licensingservice.interceptor.UserContextInterceptor
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:3000/user

name: prod
