spring:
  datasource:
    password: 124563
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.17.197.203/sca?useSSL=false
    username: yeonon
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update

  cloud:
    stream:
      bindings:
        inboundOrgChange:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
          binder: remote-rabbit
      binders:
        remote-rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 172.17.197.203
                port: 5672
                username: admin
                password: 124563
  redis:
    host: 172.17.197.203
    port: 8090


eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.18.0.4:8761/eureka



feign:
  client:
    config:
      organizationservice:
        requestInterceptors:
          - top.yeonon.licensingservice.interceptor.UserContextInterceptor
security:
  oauth2:
    resource:
      user-info-uri: http://172.18.0.7:3000/user

name: dev-change-3


